apiVersion: v1
kind: Service
metadata:
  name: medilearn-service
  labels:
    app: medilearn   # IMPORTANT for ServiceMonitor
spec:
  type: NodePort
  selector:
    app: medilearn
  ports:
    - name: http   # 🔥 REQUIRED
      port: 3000
      targetPort: 3000
      nodePort: 30007